### ISSUE TITLE
Hướng dẫn cài đặt

### ISSUE THREAD

**Issue by vfic** [01885404983/HelpdeskSystem#1]
Bác ơi, cho e xin hướng dẫn cài đặt và 1 vài hình ảnh.
Thanks

**Comment by 01885404983** [comment]
Đây chỉ là bài tập bên trường thôi, lúc nộp bài này hệ thống vẫn chưa hoàn thành và em không có dự định làm tiếp nên không dùng được trong thực tế đâu ạ.
